### ISSUE TITLE
Enhance `versions` configuration to accept options object

### ISSUE THREAD

**Issue by david-luna** [watson/test-all-versions#13]
There are a couple of scenarios where a more concise configuration of `versions` property.
- Some of the packages you're testing have a bad version within the range you want to test. There should be a way to exclude them.
- Some packages release patches very frequently [@aws-sdk clients for example](https://www.npmjs.com/package/@aws-sdk/client-s3?activeTab=versions) and we would want to test on a subset to speed up testing. Ref: https://github.com/elastic/apm-agent-nodejs/issues/2020

The proposal is to allow to pass an object into `versions` property to be more specific in which version we would want to test. That object would have the following props:
- `include` (required): the range to include in testing. Same effect that the `versions` string
- `exclude` (optional): the range of versions to exclude. Versions matching this range would be removed from the include list if present.
- `mode` (optional):  the way you want to pick versions from the ones resolved based on include/exclude. Possible values would be
  - `latest-majors`: only pick the latest major versions
  - `latest-minors`: only pick the latest minor versions
  - `max-{N}`: where {N} is a number. Pick 1st, last and {N} in between

At https://github.com/elastic/apm-agent-nodejs there is an implementation using a sibling property and a script which does the version resolution and updates the `versions` property. I think it could be easy to port it here.

Samples of the prop being used:
- https://github.com/elastic/apm-agent-nodejs/blob/22205e313ffd09f5a3becec49e287f86929bb898/.tav.yml#L65
- https://github.com/elastic/apm-agent-nodejs/blob/22205e313ffd09f5a3becec49e287f86929bb898/.tav.yml#L467
the script: https://github.com/elastic/apm-agent-nodejs/blob/main/dev-utils/update-tav-versions.js

**Comment by watson** [comment]
> Some of the packages you're testing have a bad version within the range you want to test. There should be a way to exclude them.

The way we've done this in the past is just to break up the semver into two parts. E.g to exclude version `1.2.3` you could for example write `<1.2.3 >1.2.3`

> Some packages release patches very frequently [@aws-sdk clients for example](https://www.npmjs.com/package/@aws-sdk/client-s3?activeTab=versions) and we would want to test on a subset to speed up testing

Good point.

I like your idea of allowing an object instead of a string.

It's not clear to me how you would expect `mode: latest-*` to work though. Here is what I expect that you want them to mean (if choosing between this list of version: `1.0.0`, `1.0.1`, `1.0.2`, `1.1.0`, `1.1.1`, `1.1.2`, `2.0.0`, `2.0.1`, `2.0.2`):

- `latest-majors`: `1.1.2`, `2.0.2`
- `latest-minors`: `1.0.2`, `1.1.2`, `2.0.2`

However, if that's the intent, I think the names are confusing. In my head, they should be renamed:

- `latest-majors` -> `latest-minors`
- `latest-minors` -> `latest-patches`

Regarding `max-{N}`, which versions in-between is supposed to be selected? Say you have `1.0.0`, `1.0.1`, `1.0.2`, `1.0.3`, `1.0.4`, `1.0.5` and you use `max-2`. As far as I understand it, `1.0.0` and `1.0.5` are pre-selected and the `2` is supposed to then select between 2 of the 4 remaining: `1.0.1`, `1.0.2`, `1.0.3`, `1.0.4` - but which? Should it try to evenly space out the selection? Should it pick at random? Should it pick the latest?

**Comment by david-luna** [comment]
> The way we've done this in the past is just to break up the semver into two parts.

Yes, it's a good technique :)  IMHO this way is more explicit of what we are excluding for testing. Here is a real use case
https://github.com/elastic/apm-agent-nodejs/blob/08a8bce0ae87e6305e84278713dbc7974378cc62/.tav.yml#L414

```yaml
include: '>=4 <5'
exclude: '4.0.1 || >=4.16.0 <=4.16.2'
```
is equivalent to 
```yaml
versions: '4.0.0 || >4.0.1 <4.16.0 || >4.16.2 <5'
```

> However, if that's the intent, I think the names are confusing. In my head, they should be renamed:

I have no strong opinion about the naming since I think is a matter of perspective. A good description in the docs should be enough to explain the intent to any user.

> Regarding max-{N}, which versions in-between is supposed to be selected?...

The selection is evenly across all the versions in between. you can check the implementation here.
https://github.com/elastic/apm-agent-nodejs/blob/08a8bce0ae87e6305e84278713dbc7974378cc62/dev-utils/update-tav-versions.js#L228

> Should it pick at random? Should it pick the latest?

The idea behind `max-{N}` is to test evenly across the releases between a range. Picking them randomly or latest may focus the test in a specific subrange (specially latest) which at least is not desired in https://github.com/elastic/apm-agent-nodejs

Maybe we could be more explicit on which is the strategy for picking:
- `max-5-evenly`: take 5 versions in between evenly
- `max-5-random`: take 5 versions in between randomly
- `max-5-latest`: take the latest 5 versions before the upper edge

**Comment by watson** [comment]
Thanks for explaining. Expanding on your idea of supporting different algorithms for the `max-{N}` mode, I couldn't help think if it would be possible to test only the most "important" versions - so what's an important version? I guess for an APM agent, it would be the N most downloaded versions right? So we could theoretically make a mode (say `max-5-popular`) that would query `https://api.npmjs.org/versions/{package}/last-week` and from that list select the 5 most downloaded versions. Obviously it would need to fall back to for example `max-5-evenly` if the HTTP request failed.

**Comment by watson** [comment]
I've started a PR to implement this feature (still WIP): https://github.com/watson/test-all-versions/pull/14

I think I found a bug in the [`getMax`](https://github.com/elastic/apm-agent-nodejs/blob/08a8bce0ae87e6305e84278713dbc7974378cc62/dev-utils/update-tav-versions.js#L228-L234) function from in the agent repo, where an incorrect number of versions would be returned. So I've implemented a different algorithm in the PR.
