### ISSUE TITLE
Option to continue running tests after a failure

### ISSUE THREAD

**Issue by torfsen** [watson/test-all-versions#5]
Currently, `tav` exits after the first test failure. I'd love to be able to have an option which allows me to continue through all versions under test even if some of them fail -- knowing which versions exactly are affected by a failing test case is very useful to know.

**Comment by watson** [comment]
This is possible with the `--compat` flag:
https://github.com/watson/test-all-versions#options

That will give you an overview over which versions fails and which succeeds.
